---
aqualog_proxy_internal_port: 80 # This is the port listening inside the container, not the port exposed to the host machine.
aqualog_proxy_exposed_port: 80

aqualog_backend_internal_port: 8000 # This is the port listening inside the container, not the port exposed to the host machine.
aqualog_backend_exposed_port: 8001

aqualog_frontend_internal_port: 8000 # This is the port listening inside the container, not the port exposed to the host machine.
aqualog_frontend_exposed_port: 8002

aqualog_auth_internal_port: 9000 # This is the port listening inside the container, not the port exposed to the host machine.
aqualog_auth_exposed_port: 8000
aqualog_auth_internal_port_https: 9443 # This is the port listening inside the container, not the port exposed to the host machine.
aqualog_auth_exposed_port_https: 8443

aqualog_backend_image: "ghcr.io/cylindric/aqualog-backend:latest"
aqualog_frontend_image: "ghcr.io/cylindric/aqualog-frontend:latest"

# AUTH SERVER SETTINGS
# echo "aqualog_authentik_password: $(openssl rand -base64 36 | tr -d '\n')"
aqualog_authentik_password: ""
aqualog_authentik_user: "authentik"

# echo "aqualog_authentik_secret_key: $(openssl rand -base64 60 | tr -d '\n')"
aqualog_authentik_secret_key: ""

# COMMON SETTINGS
aqualog_oauth_client_id: ""

# echo "aqualog_db_password: \"$(openssl rand -base64 36)\""
aqualog_db_password: ""

# PROXY SETTINGS
aqualog_cf_api_token: ""