# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list
    silent: true

  build-all:
    desc: Build all docker images
    cmds:
      - cd backend && task build
      - cd frontend && task build

  up:
    desc: Start all docker containers
    cmds:
      - docker-compose up
