---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: aqualog
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: backend
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-server-data-pvc
  namespace: aqualog
  labels:
    app: auth-server
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-server-template-pvc
  namespace: aqualog
  labels:
    app: auth-server
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: aqualog
  labels:
    app: auth-server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: auth-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: ghcr.io/goauthentik/server:2026.5.4
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
            name: auth-http
            protocol: TCP
          - containerPort: 9443
            name: auth-https
            protocol: TCP
        env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: "auth-db.aqualog.svc.cluster.local"
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: "authentik"
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          value: "..."
        - name: AUTHENTIK_POSTGRESQL__USER
          value: "..."
        - name: AUTHENTIK_SECRET_KEY
          value: "..."
        - name: AUTHENTIK_ERROR_REPORTING__ENABLED
          value: "true"
        volumeMounts:
        - mountPath: "/data"
          subPath: authdata
          name: auth-server-data-volume
        - mountPath: "/templates"
          subPath: authtemplates
          name: auth-server-template-volume
      restartPolicy: Always
      volumes:
        - name: auth-server-data-volume
          persistentVolumeClaim:
            claimName: auth-server-data-pvc
        - name: auth-server-template-volume
          persistentVolumeClaim:
            claimName: auth-server-template-pvc
